### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by marcelmokos** [jwerle/shamirs-secret-sharing#1]
Hi Joseph Werle, 

I was playing with your library and here is a demo using codesandbox you may use in the docs.  

https://codesandbox.io/s/shamirs-secret-sharing-pcsbk

**Comment by jwerle** [comment]
@marcelmokos https://github.com/jwerle/shamirs-secret-sharing/commit/40b3a1a3ece49d1009e301a8ac1ac62ac5476c6d
